version: '2.1'

services:

  # сервер, где запущено приложение
  auth-proxy-prod:
    image: auth-proxy-prod
    container_name: auth-proxy-prod
    restart: always
    dns:
      - '194.190.37.16'
      - '194.190.23.68'
    ports:
      - 4400:4400
    volumes: 
      # Пишем логи в общий том, чтобы они сохранялись в Эластик
      - app-logs:/app/logs
      # чтобы можно было подсунуть новый db.yaml
      - ./configs:/app/configs
      # Перенаправляем сообщение об ошибках в файл
    command: bash -c "cd /app && ./auth-proxy -env=prod -serve=4400 2>/app/logs/auth-proxy.log"



networks:
  default:
    external:
      name: auth_proxy_network

# Данные логов
volumes:
  app-logs:
    external: true
